### ISSUE TITLE
Add TAD and LDOS to data set

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/lastdose#1]
# Summary

As a user, I want lastdose to add time after dose and last dose amount columns to my data set. 

# Tests

- tests/testthat/test-lastdose.R
  - doses at time zero
  - time ties (q12h dosing)
  - don't fill back 
  - customize fill
  - doses don't start at time zero
  - lastdose_df
  - required columns
  - non-numeric data throws error
  - records out of order throws error
  - tad and ldos are NA when time is NA
  - error for missing values in ID,evid,ii,addl
  - NA amt is error for dosing record, ok otherwise

**Comment by barrettk** [comment]
Notes pasted below:
1. The user will pass in NMTRAN-formatted analysis data as a data frame. 
1. The analysis data frame will have the following required columns
    - `ID` or `id` - the user id number
    - `TIME` or `time` - the time since first observation 
    - `AMT` or `amt` - the dose amount
    - `EVID` or `evid` - the record event id; `evid` equal to 1 or 4
      will be considered dosing records
1. The analysis data frame will have the following optional columns
    - `ADDL` or `addl` - additional doses to administer
    - `II` or `ii` - the dosing interval
1. All required and optional columns must be numeric; an error is generated
   otherwise.
1. The following columns must not contain missing values: ID, `evid`, `ii`, 
   `addl`; an error is generated if missing values are found.
1. When `time` contains missing values, both `TAD` and `LDOS` will be set 
   to missing also.
1. An error is generated when missing values are found in dosing records 
   (evid 1 or 4) but no error is generated when missing values found in 
   non-dosing records.
1. The input data set must be sorted by time within individual; an error is 
   generated otherwise.
1. By default, doses prior to the first dosing record will be calculated as 
   time before the first dose and be expressed as negative numbers.
1. The user may choose to fill in `TAD` for records prior to the first dose
   with a single user-specified fill value.
1. The single use-specified fill value will be use to fill in all values for 
   `TAD` when no dosing records are found for a particular individual.
1. The `lastdose()` function will append columns called `TAD` and `LDOS` to 
   the input data indicating the time after dose and last dose, respectively.
1. The user can choose how to handle `TAD` when additional doses (via `ADDL`
   happen at the same time as another record in the data set.  By default, 
   records at the same time are sorted ascending by dose amount so that 
   observation records happen prior to doses.  This makes the observation a 
   trough concentration. Alternatively, records can be sorted descending 
   by dose amount so that doses happen first.  This makes the observation 
   a peak. The sorting that is done has no bearing on records explicitly listed
   in the input data.
