### ISSUE TITLE
Choose how TAD and LDOS are filled

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/lastdose#3]
# Summary

As a user, I want to be able to choose how TAD and LDOS are filled/entered in the dataset.

# Tests

- tests/testthat/test-lastdose.R
  - don't fill back
  - customize fill
  - doses don't start at time zero

**Comment by barrettk** [comment]
Notes:
1. By default, doses prior to the first dosing record will be calculated as 
   time before the first dose and be expressed as negative numbers.
1. The user may choose to fill in `TAD` for records prior to the first dose
   with a single user-specified fill value.
1. The user can choose how to handle `TAD` when additional doses (via `ADDL`
   happen at the same time as another record in the data set.  By default, 
   records at the same time are sorted ascending by dose amount so that 
   observation records happen prior to doses.  This makes the observation a 
   trough concentration. Alternatively, records can be sorted descending 
   by dose amount so that doses happen first.  This makes the observation 
   a peak. The sorting that is done has no bearing on records explicitly listed
   in the input data.
